import express from 'express';
import session from 'express-session';
import dotenv from 'dotenv';
import cors from 'cors';
import {errorHandler} from "./middleware/errorHandler.js";
import taikhoanRoute from "./route/taikhoan.js";
import phongRoute from "./route/Phong.js";
import toanhaRoute from "./route/Toanha.js";
import loaiphongRoute from "./route/LoaiPhong.js";
import hoadonRoute from "./route/HoaDon.js";
import chitiethoadonRoute from "./route/ChiTietHoaDon.js";
import hosoRoute from "./route/HoSo.js";
import hopdongRoute from "./route/HopDong.js";
import dichvuRoute from "./route/DichVu.js";
import chitietdichvuRoute from "./route/ChiTietDichVu.js";
import hoadondichvuRoute from "./route/HoaDonDichVu.js";
import nguoithanRoute from "./route/NguoiThan.js";
import sinhvienRoute from "./route/SinhVien.js";
import lichsuravaoRoute from "./route/LichSuRaVao.js";
import kyluatRoute from "./route/KyLuat.js";
import nguoidungRoute from "./route/NguoiDung.js";
import gopyRoute from "./route/GopYRoute.js";
import phanquyenRoute from "./route/PhanQuyen.js";
import thongbaoRoute from "./route/ThongBao.js";
import tinnhanRoute from "./route/TinNhan.js";
import binhluanRoute from "./route/BinhLuan.js";
import tuongtacRoute from "./route/TuongTac.js";
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/uploads', express.static('uploads'));
app.use(session({
  secret: 'secret-session',
  resave: false,
  saveUninitialized: true,
}));
app.use('/', taikhoanRoute);
app.use('/room', phongRoute);
app.use('/toa_nha', toanhaRoute);
app.use('/loai_phong', loaiphongRoute);
app.use('/hoa_don', hoadonRoute);
app.use('/chi_tiet_hoa_don', chitiethoadonRoute);
app.use('/ho_so', hosoRoute);
app.use('/hop_dong', hopdongRoute);
app.use('/dich_vu',dichvuRoute);
app.use('/chi_tiet_dich_vu',chitietdichvuRoute);
app.use('/hoa_don_dich_vu',hoadondichvuRoute);
app.use('/nguoi_than',nguoithanRoute);
app.use('/sinh_vien',sinhvienRoute);
app.use('/lich_su_ra_vao',lichsuravaoRoute);
app.use('/ky_luat',kyluatRoute);
app.use('/nguoi_dung',nguoidungRoute);
app.use('/gop_y',gopyRoute);
app.use('/phan_quyen',phanquyenRoute);
app.use('/thong_bao',thongbaoRoute);
app.use('/tin_nhan',tinnhanRoute);
app.use('/binh_luan',binhluanRoute);
app.use('/tuong_tac',tuongtacRoute);
app.use(errorHandler);
const PORT = 3000;
app.listen(PORT, () => console.log(`http://localhost:${PORT}`));